apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: biovalidator
  name: biovalidator
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: biovalidator
  template:
    metadata:
      labels:
        app: biovalidator
    spec:
      imagePullSecrets:
        - name: $DOCKER_PULL_SECRET
      containers:
        - name: biovalidator
          image: $DOCKER_IMAGE_NAME
          imagePullPolicy: Always
          ports:
            - containerPort: 3020
          args:
            - "--baseUrl"
            - "/biosamples/biovalidator"
          env:
            - name: HTTP_PROXY
              value: $HTTP_PROXY
            - name: HTTPS_PROXY
              value: $HTTP_PROXY
            - name: NO_PROXY
              value: $NO_PROXY
            - name: http_proxy
              value: $HTTP_PROXY
            - name: https_proxy
              value: $HTTP_PROXY
            - name: no_proxy
              value: $NO_PROXY

---
apiVersion: v1
kind: Service
metadata:
  name: biovalidator-service
spec:
  type: NodePort
  selector:
    app: biovalidator
  ports:
    - protocol: TCP
      port: 3020
      targetPort: 3020
